### PR TITLE
[RBrowser] Continue of Tabs types

### PR DESCRIPTION
**Pull request by Falcort**
New PR for the next part of the tabs types like the image viewer

### CODE REVIEW

**Comment by Falcort** [comment]
@linev In order to debug the macros i solved the issue that you cannot open .C files

**Comment by linev** [comment]
Thibault

I resolve basic problem with code editor - you have to assign controller when loading fragment.
See my last commit

**Comment by Falcort** [comment]
Ok, this will solve some problems, i will do a complete change after the + as we were discussiong, and use that for sure
Could you please tell me what command exactly i am supposed to do to take your changes ? without srewing up my branch please ?

**Comment by linev** [comment]
> Could you please tell me what command exactly i am supposed to do to take your changes ? 
> without srewing up my branch please ?

I just fix a bug - now again one could run a scripts. Just rebase your "RBrowser-TabsTypes" branch.
Now you could try to implement "+" sign working with many editors and and many image viewers.
Once you are done, I will merge this PR

**Comment by Falcort** [comment]
Ok i will try, you can already have multiples codes editors, and i am doing the images viewer as we speak

**Comment by Falcort** [comment]
When you mean, image viewer, you mean only image contained in root files like in gallery.root, or image that are on the file explorer or both ?

**Comment by linev** [comment]
> When you mean, image viewer, you mean only image contained in root files like in gallery.root, or image that are on the file explorer or both ?

For now is just image in current directory - like image.png.
This is how double-click on image is working now - it returns "FIMG:" reply plus base64 coded string, which can be directly used in ``
Later I can try to generate image from ROOT objects

**Comment by Falcort** [comment]
Ok ok, it was just to be sure

**Comment by Falcort** [comment]
@linev i have finished the based implementation of the image viewer, for the moment it only take .png & .jpg pictures, do you want more file extensions ?

I also need to change the Root6/7 Canvas to open the good version of canvas, and i will be done with the +

**Comment by Falcort** [comment]
@linev, sorry to repost but could you provide me some informations about my last comment please ?

**Comment by linev** [comment]
> @linev i have finished the based implementation of the image viewer, for the moment it only take .png & .jpg pictures, do you want more file extensions ?

Check that extensions are supported by browsers with base64 coding?
I think, not that many. Of course, all supported should be implemented in RBrowser

**Comment by Falcort** [comment]
Ok so i found the following supported format : 
- BMP
- GIF
- ICO
- JPG
- PNG
- SVG
- WebP

They all work, but not SVG, so i commented it out for now.

All that remains now is the selection of Root6 or Root7 for canvas, and i found the line that you told me, but i can't find a way to make it work, could you help me a bit more please ?

**Pull request closed without merging**
